modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Grindstone%20Sharper%20Tools"
logoFile="icon.png"

[[mods]]
modId="grindstonesharpertools"
version="3.0"
displayName="Grindstone Sharper Tools"
displayURL="https://curseforge.com/minecraft/mc-mods/grindstone-sharper-tools"
authors="Rick South"
description='''The grindstone can sharpen tools, temporarily increasing their damage dealt.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.grindstonesharpertools]]
    modId="collective"
    mandatory=true
    versionRange="[6.18,)"
    ordering="NONE"
    side="BOTH"