modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Collective"
logoFile="icon.png"

[[mods]]
modId="collective"
version="6.26"
displayName="Collective"
displayURL="https://curseforge.com/minecraft/mc-mods/collective"
authors="Rick South"
description='''Collective is a shared library with common code for all of Serilum's mods.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3
'''

[[dependencies.collective]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.collective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"