modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Village%20Names"
logoFile="icon.png"

[[mods]]
modId="randomvillagenames"
version="3.0"
displayName="Random Village Names"
displayURL="https://curseforge.com/minecraft/mc-mods/random-village-names"
authors="Rick South"
description='''Gives all villages a random name from a preset list. Uses the Areas mod to display the name in the GUI.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randomvillagenames]]
    modId="collective"
    mandatory=true
    versionRange="[6.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomvillagenames]]
    modId="areas"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="BOTH"